export const LOGIN = "/login"
export const REGISTER = "/register"
export const HOME = "/home"
export const CAMPAIGN = "/campaign/"
export const ADMIN = "/admin"
export const NEW_CAMPAIGN = "/new-campaign"
export const PENDING = "/pending"
